INSERT INTO envanterDB.DEPO_URUN_TBL (VERSION,CREATE_USR_ID,CREATE_GMT,USR_ID,GMT,STATUS,COMMENT_,DEPO_ID,URUN_ID,ADET) VALUES
	 (1,NULL,NULL,NULL,NULL,NULL,NULL,1,1,55),
	 (1,NULL,NULL,NULL,NULL,NULL,NULL,2,1,45),
	 (1,NULL,NULL,NULL,NULL,NULL,NULL,1,2,11);
