INSERT INTO envanterDB.DEPO_TBL (VERSION,CREATE_USR_ID,CREATE_GMT,USR_ID,GMT,STATUS,COMMENT_,ADI,ADRES,BOLGE_ADI,IL_ADI) VALUES
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,'M.B.İSTANBUL MERKEZ DEPOSU','SANCAKTEPE / İSTANBUL','Marmara Bölgesi','İSTANBUL'),
	 (1,NULL,NULL,NULL,NULL,NULL,NULL,'M.B.İSTANBUL AVRUPA YAKASI MERKEZ DEPOSU','SULTANGAZİ / İSTANBUL','Marmara Bölgesi','İSTANBUL');
