CREATE TABLE URUN_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  ADI varchar(255) NOT NULL,
  KATEGORI_ID INT NOT NULL,
  ADET INT not null,
  MIN_ADET INT not null,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE KATEGORI_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  ADI varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE DEPO_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  ADI varchar(255) NOT NULL,
  ADRES varchar(255) NOT NULL,
  BOLGE_ADI varchar(255) NOT NULL,
  IL_ADI varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE DEPO_URUN_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  DEPO_ID INT NOT NULL,
  URUN_ID INT NOT NULL,
  ADET INT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



CREATE TABLE ENVANTER_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  URUN_ID INT NOT NULL,
  DEPO_ID INT NOT NULL,
  GIRIS_TRH DATE,
  CIKIS_TRH DATE,
  ADET INT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE ENVANTER_HSTRY_TBL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  VERSION    INT,
  CREATE_USR_ID INT,
  CREATE_GMT DATE,
  USR_ID INT,
  GMT DATE,
  STATUS VARCHAR(1),
  COMMENT_ VARCHAR(512),
  ENVANTER_ID INT NOT NULL,
  URUN_ID INT ,
  DEPO_ID INT ,
  GIRIS_TRH DATE,
  CIKIS_TRH DATE,
  ADET INT,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;