INSERT INTO envanterDB.URUN_TBL (VERSION,CREATE_USR_ID,CREATE_GMT,USR_ID,GMT,STATUS,COMMENT_,ADI,KATEGORI_ID,ADET,MIN_ADET) VALUES
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bilgisayar Kasası',1,100,10),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bilgisayar Monitör',1,100,10),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bilgisayar Klavye',1,100,3),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Fare (mouse)',1,100,3);
